<?php
	
	Form::macro('selectState', function($name, $selected = null, $options = array()) {
		$states = array(
					'AL'=>"AL",
					'AK'=>"AK",
					'AZ'=>"AZ",
					'AR'=>"AR",
					'CA'=>"CA",
					'CO'=>"CO",
					'CT'=>"CT",
					'DE'=>"DE",
					'DC'=>"DC",
					'FL'=>"FL",
					'GA'=>"GA",
					'HI'=>"HI",
					'ID'=>"ID",
					'IL'=>"IL",
					'IN'=>"IN",
					'IA'=>"IA",
					'KS'=>"KS",
					'KY'=>"KY",
					'LA'=>"LA",
					'ME'=>"ME",
					'MD'=>"MD",
					'MA'=>"MA",
					'MI'=>"MI",
					'MN'=>"MN",
					'MS'=>"MS",
					'MO'=>"MO",
					'MT'=>"MT",
					'NE'=>"NE",
					'NV'=>"NV",
					'NH'=>"NH",
					'NJ'=>"NJ",
					'NM'=>"NM",
					'NY'=>"NY",
					'NC'=>"NC",
					'ND'=>"ND",
					'OH'=>"OH",
					'OK'=>"OK",
					'OR'=>"OR",
					'PA'=>"PA",
					'RI'=>"RT",
					'SC'=>"SC",
					'SD'=>"SD",
					'TN'=>"TN",
					'TX'=>"TX",
					'UT'=>"UT",
					'VT'=>"VT",
					'VA'=>"VA",
					'WA'=>"WA",
					'WV'=>"WV",
					'WI'=>"WI",
					'WY'=>"WY"
				);

		return Form::select($name, $states, $selected, $options);
		
	});